worker_processes auto;

events {
    worker_connections 1024;
    # how many connections it can simultaniously handle
}

http {
    resolver 127.0.0.11 valid=10s;  # Docker's internal DNS
    upstream user_service {
        server application:8000;   # Service name instead of individual containers
    }

    server {
        listen 80;

        location / {
          proxy_pass http://user_service;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
