

services:
  mongodb:
    image: mongo:6-jammy
    container_name: py-api-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root