

services:
  application:
    image: py-api:latest
    container_name: py-api-server
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    volumes:
      - "./logs:/home/app/logs"

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: py-api-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin