

services:
  api-geteway:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - './api-gateway:/etc/nginx/'
    depends_on:
      - application

  application:
    image: py-api:latest
    # container_name: py-api-server
    expose:
      - 8000
    depends_on:
      - mongodb
    volumes:
      - "./logs:/home/app/logs"
    build:
      context: .
      dockerfile: dockerfile
    deploy:
      replicas: 3

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: py-api-mongodb
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin