
services:
  user_service:
    image: user_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./env:/app/env
      - ./logs:/app/logs
