FROM alpine:latest

# Install Python and required build dependencies
RUN apk add --no-cache \
    python3 \
    py3-pip

# create non-root user
RUN adduser -D -h /app app
USER app

# set working directory
WORKDIR /app

# Copy source code
COPY . .


EXPOSE 8000

CMD [ ".venv/bin/python3", "start_service.py" ]
