version: '3.8'

services:
  auth_service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: auth_service
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    depends_on:
      - mongodb
      
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: auth_service_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017