FROM alpine:latest

# Install Python and required build dependencies
RUN apk add --no-cache \
    python3 \
    py3-pip

# create non-root user
RUN adduser -D -h /app app

# set working directory
WORKDIR /app
EXPOSE 8000

# Copy source code
COPY . .
RUN chmod +x ./entrypoint.sh
USER app
ENTRYPOINT ["./entrypoint.sh"]
